---
- hosts: all
  become: true
  tasks:
    - name: Install Git
      apt: name=git state=latest

    - name: Install Python3
      apt: name=python3 state=latest

    - name: Install Pipenv
      apt: name=pipenv state=latest
